---
title: "TG Ball Edit Analysis"
author: "Bradford Johnson"
format:
  revealjs: 
    theme: simple
---

## Ball Edit % Trends

```{r}
# load packages
library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
library(scales)

# load data
tg_df <- read_excel("C:/Users/Bradf/OneDrive/Desktop/tg-data.xlsx", "tg-data") %>%
  clean_names()

tg_df$date <- excel_numeric_to_date(tg_df$date)

# [Apr 1st - Oct 14 2022] - percent edit plot
  tg_df %>%
    ggplot(aes(x = date, y = percent_edit)) +
    geom_line() +
    geom_smooth(method = "lm", se = FALSE, color = "red") +
    scale_y_continuous(labels = scales::percent_format(accuracy = 0.01)) +
    labs(title = "",
      x = "",
      y = "Ball Edit %") +
    theme_classic()
```

## Weekly Average: Ball Edit %

```{r}
# load packages
library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
library(scales)

# load data
tg_df <- read_excel("C:/Users/Bradf/OneDrive/Desktop/tg-data.xlsx", "tg-data") %>%
  clean_names()

tg_df$date <- excel_numeric_to_date(tg_df$date)
# average ball edit percent - week
  tg_df %>%
    mutate(week = week(date)) %>%
    group_by(week) %>%
    summarise(avg_edit_percent = mean(percent_edit)) %>%
    ggplot(aes(x = week, y = avg_edit_percent, fill = avg_edit_percent)) +
    geom_col() +
    scale_y_continuous(labels = scales::percent_format(accuracy = 0.01)) +
    scale_fill_gradient(low = "green", high = "red") +
    labs(title = "",
         x = "Week Number",
         y = "") +
    theme_classic() +
    theme(legend.position = "none")
```

## Monthly Average: Ball Edit %

```{r}
library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
library(scales)

# load data
tg_df <- read_excel("C:/Users/Bradf/OneDrive/Desktop/tg-data.xlsx", "tg-data") %>%
  clean_names()

tg_df$date <- excel_numeric_to_date(tg_df$date)
# average ball edit percent - month
  tg_df %>%
    mutate(month = month(date, label = TRUE, abbr = TRUE)) %>%
    group_by(month) %>%
    summarise(avg_edit_percent = mean(percent_edit)) %>%
    ggplot(aes(x = month, y = avg_edit_percent, fill = avg_edit_percent)) +
    geom_col() +
    scale_y_continuous(labels = scales::percent_format(accuracy = 0.01)) +
    scale_fill_gradient(low = "green", high = "red") +
    labs(title = "",
         x = "",
         y = "") +
    theme_classic() +
    theme(legend.position = "none")
```
